const DAYS=['일요일','월요일','화요일','수요일','목요일','금요일','토요일'];
const COLORS=['#789aa2','#e6bd62','#dc8862','#8aa17a','#b38aa7','#78a892','#c59366'];
const sample=[{start:0,end:420,title:'꿈나라',detail:'충분히 자고 개운하게 일어나기',color:COLORS[0]},{start:420,end:480,title:'씻고 아침 먹기',detail:'가벼운 아침과 하루 준비',color:COLORS[1]},{start:480,end:600,title:'아침 여유',detail:'책을 읽거나 오늘 할 일 확인',color:'#d8c996'},{start:600,end:960,title:'업무 미팅, 보고서 작성',detail:'중요한 일부터 집중해서 끝내기',color:COLORS[2]},{start:960,end:1200,title:'저녁 약속',detail:'약속 장소 링크나 준비물을 메모해 보세요.',color:COLORS[3]},{start:1200,end:1380,title:'운동 가기',detail:'운동복과 물 챙기기',color:COLORS[4]},{start:1380,end:1440,title:'꿈나라',detail:'내일을 위해 쉬기',color:COLORS[0]}];
const clone=x=>JSON.parse(JSON.stringify(x));
let state=JSON.parse(localStorage.getItem('roundDayState')||'null')||{active:'p1',plans:[{id:'p1',title:'나의 기본 일주일',created:'2026. 8. 8.',days:Object.fromEntries(DAYS.map(d=>[d,clone(sample)]))},{id:'p2',title:'여행 1주차 계획',created:'2026. 8. 15.',days:Object.fromEntries(DAYS.map(d=>[d,clone(sample).map((x,i)=>i===3?{...x,title:'여행지 둘러보기'}:x)]))}]};
let dayIndex=new Date().getDay(), selected=-1, editing=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem('roundDayState',JSON.stringify(state))} function plan(){return state.plans.find(p=>p.id===state.active)||state.plans[0]} function items(){return plan().days[DAYS[dayIndex]]||[]}
function fmt(m){m=(m+1440)%1440;return `${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`}
function currentMinute(){const now=new Date();return now.getHours()*60+now.getMinutes()}
function currentItemIndex(){return items().findIndex(it=>currentMinute()>=it.start&&currentMinute()<it.end)}
function render(){const now=new Date(),isToday=dayIndex===now.getDay(),nowIndex=isToday?currentItemIndex():-1;if(selected<0)selected=Math.max(0,nowIndex);$('#todayChip').textContent=`${now.getMonth()+1}월 ${now.getDate()}일`;$('#todayName').textContent=DAYS[dayIndex];$('#planName').textContent=plan().title;$('#centerDate').textContent=isToday?`지금 ${fmt(currentMinute())}`:`${now.getMonth()+1}.${now.getDate()}`;$('#centerProgress').textContent=isToday&&nowIndex>=0?items()[nowIndex].title:`${items().length}개의 일정`;draw();drawNowMarker();renderSelected();renderLists()}
function draw(){const c=$('#clock'),ctx=c.getContext('2d'),S=c.width,C=S/2,R=314;ctx.clearRect(0,0,S,S);ctx.beginPath();ctx.arc(C,C,R,0,Math.PI*2);ctx.fillStyle='#fffdf8';ctx.fill();items().forEach((it,i)=>{let a=it.start/1440*Math.PI*2-Math.PI/2,b=it.end/1440*Math.PI*2-Math.PI/2;ctx.beginPath();ctx.moveTo(C,C);ctx.arc(C,C,R,a,b);ctx.closePath();ctx.fillStyle=it.color;ctx.globalAlpha=i===selected?1:.82;ctx.fill();ctx.globalAlpha=1;ctx.strokeStyle='#f8f4ec';ctx.lineWidth=5;ctx.stroke();let mid=(a+b)/2,rr=i===selected?226:218;ctx.save();ctx.translate(C+Math.cos(mid)*rr,C+Math.sin(mid)*rr);ctx.rotate(mid+Math.PI/2);ctx.textAlign='center';ctx.fillStyle='#fff';ctx.font='700 18px Noto Sans KR';let label=it.title.length>10?it.title.slice(0,9)+'…':it.title;ctx.fillText(label,0,0);ctx.font='600 14px DM Sans';ctx.fillText(`${fmt(it.start)}–${fmt(it.end)}`,0,23);ctx.restore()});for(let h=0;h<24;h++){let a=h/24*Math.PI*2-Math.PI/2,x1=C+Math.cos(a)*(R-10),y1=C+Math.sin(a)*(R-10),x2=C+Math.cos(a)*(R-25),y2=C+Math.sin(a)*(R-25);ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.strokeStyle='#ffffffaa';ctx.lineWidth=h%3===0?4:2;ctx.stroke();if(h%3===0){ctx.fillStyle='#5d5a52';ctx.font='700 15px DM Sans';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(h,C+Math.cos(a)*(R+23),C+Math.sin(a)*(R+23))}}
}
function drawNowMarker(){if(dayIndex!==new Date().getDay())return;const c=$('#clock'),ctx=c.getContext('2d'),C=c.width/2,R=314,a=currentMinute()/1440*Math.PI*2-Math.PI/2;ctx.beginPath();ctx.moveTo(C+Math.cos(a)*82,C+Math.sin(a)*82);ctx.lineTo(C+Math.cos(a)*(R+4),C+Math.sin(a)*(R+4));ctx.strokeStyle='#292b27';ctx.lineWidth=5;ctx.lineCap='round';ctx.stroke();ctx.beginPath();ctx.arc(C+Math.cos(a)*(R+4),C+Math.sin(a)*(R+4),9,0,Math.PI*2);ctx.fillStyle='#292b27';ctx.fill()}
$('#clock').addEventListener('click',e=>{const r=e.target.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*720-360,y=(e.clientY-r.top)/r.height*720-360;let ang=Math.atan2(y,x)+Math.PI/2;if(ang<0)ang+=Math.PI*2;const minute=ang/(Math.PI*2)*1440;selected=Math.max(0,items().findIndex(it=>minute>=it.start&&minute<it.end));render()});
function renderSelected(){let it=items()[selected]||items()[0];if(!it){$('#selectedCard').innerHTML='<p>아직 일정이 없어요. 계획을 만들어 보세요.</p>';return}$('#selectedCard').innerHTML=`<div class="row"><div><span class="time">${fmt(it.start)} — ${fmt(it.end)}</span><h3>${it.title}</h3><p>${it.detail||'세부 계획을 메모해 보세요.'}</p></div><button id="editSelected">수정</button></div>`;$('#editSelected').onclick=()=>openDetail(it)}
function renderLists(){const html=state.plans.slice().reverse().map(p=>`<div class="plan-row"><div class="mini-clock"></div><div><b>${p.title}</b><small>${p.created} · 7일 계획</small></div><button class="icon-btn use-plan" data-id="${p.id}">›</button></div>`).join('');$('#recentPlans').innerHTML=html;$('#planLibrary').innerHTML=state.plans.map(p=>`<button class="library-card ${p.id===state.active?'active-plan':''}" data-id="${p.id}"><div class="mini-clock"></div><div><b>${p.title}</b><small>${p.created} · 저장된 주간 계획</small></div><span class="check">${p.id===state.active?'✓':''}</span></button>`).join('');$$('.library-card').forEach(b=>b.onclick=()=>{state.active=b.dataset.id;save();toast('이번 주 시간표를 바꿨어요');render()});$$('.use-plan').forEach(b=>b.onclick=()=>{state.active=b.dataset.id;save();switchTab('today');render()})}
function switchTab(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));$('#pageTitle').textContent=id==='today'?'동그란 하루':id==='build'?'계획 세우기':'시간표 보관함'}$$('nav button').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$('#prevDay').onclick=()=>{dayIndex=(dayIndex+6)%7;selected=-1;render()};$('#nextDay').onclick=()=>{dayIndex=(dayIndex+1)%7;selected=-1;render()};
const timeOptions=()=>Array.from({length:288},(_,i)=>`<option value="${i*5}">${fmt(i*5)}</option>`).join('');
function startWizard(){editing={step:0,title:'',days:[...DAYS],day:0,draft:clone(sample),dayDrafts:{}};wizardStep();$('#wizard').showModal()}
function wizardStep(){const w=$('#wizardBody');if(editing.step===0){w.innerHTML=`<span class="eyebrow">STEP 1 · 이름 붙이기</span><h2 class="question">어떤 일주일을<br>만들까요?</h2><div class="field"><label>계획 제목</label><input id="planTitle" value="나의 새로운 일주일" maxlength="30"></div><div class="field"><label>계획할 요일</label><div class="day-grid">${DAYS.map(d=>`<button type="button" class="selected" data-day="${d}">${d[0]}</button>`).join('')}</div></div><button class="next-btn" type="button" id="wizardNext">요일별 계획 짜기</button>`;$$('.day-grid button').forEach(b=>b.onclick=()=>b.classList.toggle('selected'));$('#wizardNext').onclick=()=>{editing.title=$('#planTitle').value.trim()||'새로운 일주일';editing.days=$$('.day-grid .selected').map(b=>b.dataset.day);editing.step=1;editing.day=0;wizardStep()}}else{const d=editing.days[editing.day],prev=DAYS[(DAYS.indexOf(d)+6)%7];editing.draft=editing.dayDrafts[d]||clone(sample);w.innerHTML=`<span class="eyebrow">${editing.day+1} / ${editing.days.length} · ${d}</span><h2 class="question">${d}은<br>어떻게 보낼까요?</h2><div class="field"><label>${prev}에 몇 시에 잘 거야?</label><div class="time-line"><select id="sleepWhen"><option value="prev">전날</option><option value="today">오늘</option></select><span></span><select id="sleepTime">${timeOptions()}</select></div></div><div class="field"><label>몇 시에 일어날 거야?</label><select id="wakeTime">${timeOptions()}</select></div><div class="schedule-stack" id="draftStack"></div><button class="next-btn" type="button" id="saveDay">${editing.day===editing.days.length-1?'계획 완성하기':'다음 요일 계획하기'}</button>`;$('#sleepTime').value=1380;$('#wakeTime').value=420;renderDraft();$('#saveDay').onclick=()=>{const wake=+$('#wakeTime').value,sleep=+$('#sleepTime').value;editing.draft[0].end=wake;editing.draft.at(-1).start=sleep;editing.dayDrafts[d]=clone(editing.draft);if(editing.day<editing.days.length-1){editing.day++;wizardStep()}else finishWizard()}}
}
function renderDraft(){let list=editing.draft;$('#draftStack').innerHTML=list.slice(1,-1).map(x=>`<div class="schedule-chip"><b>${fmt(x.start)} — ${fmt(x.end)}</b>${x.title}</div>`).join('')+`<div class="field"><label>다음엔 뭘 할까?</label><input id="newBlockTitle" placeholder="예: 산책하고 책 읽기"><div class="time-line"><input value="${fmt(list.at(-2).end)}" disabled><span>–</span><select id="newBlockEnd">${timeOptions()}</select></div></div><button type="button" class="next-btn" id="addBlock">＋ 일정 이어 붙이기</button>`;$('#newBlockEnd').value=Math.min(list.at(-2).end+60,1380);$('#addBlock').onclick=()=>addBlock()}
function addBlock(){let title=$('#newBlockTitle').value.trim(),start=editing.draft.at(-2).end,end=+$('#newBlockEnd').value;if(!title)return toast('할 일을 먼저 적어주세요');if(end<=start)return toast('끝나는 시간을 더 늦게 골라주세요');editing.draft.splice(-1,0,{start,end,title,detail:'',color:COLORS[(editing.draft.length-1)%COLORS.length]});renderDraft()}
function finishWizard(){const days=Object.fromEntries(DAYS.map(d=>[d,editing.dayDrafts[d]||clone(sample)]));let p={id:'p'+Date.now(),title:editing.title,created:new Date().toLocaleDateString('ko-KR'),days};state.plans.push(p);state.active=p.id;save();$('#wizard').close();toast('새 시간표를 만들었어요');switchTab('today');render()}
function openDetail(it){const d=$('#detailBody');editing={item:it};d.innerHTML=`<div class="field"><label>일정 이름</label><input id="detailTitle" value="${it.title}"></div><div class="field"><label>시간</label><div class="time-line"><select id="detailStart">${timeOptions()}</select><span>–</span><select id="detailEnd">${timeOptions()}</select></div><div id="conflict"></div></div><div class="field"><label>세부 계획 · 링크도 함께 저장할 수 있어요</label><textarea id="detailMemo">${it.detail||''}</textarea></div><button class="next-btn" type="button" id="saveDetail">저장하기</button>`;$('#detailStart').value=it.start;$('#detailEnd').value=it.end;$('#saveDetail').onclick=saveDetail;$('#deleteItem').onclick=()=>{if(items().length<=1)return toast('마지막 일정은 삭제할 수 없어요');plan().days[DAYS[dayIndex]]=items().filter(x=>x!==it);selected=0;save();$('#detail').close();render()};$('#detail').showModal()}
function saveDetail(){let it=editing.item,start=+$ ('#detailStart').value,end=+$ ('#detailEnd').value;const other=items().find(x=>x!==it&&start<x.end&&end>x.start);if(end<=start){$('#conflict').innerHTML='<div class="conflict">끝나는 시간은 시작 시간보다 늦어야 해요.</div>';return}if(other){$('#conflict').innerHTML=`<div class="conflict">${fmt(other.start)}부터는 ‘${other.title}’ 일정이 있어요.</div>`;return}Object.assign(it,{start,end,title:$('#detailTitle').value.trim()||'이름 없는 일정',detail:$('#detailMemo').value});items().sort((a,b)=>a.start-b.start);selected=items().indexOf(it);save();$('#detail').close();toast('일정을 수정했어요');render()}
function toast(s){const t=$('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
$('#newPlan').onclick=startWizard;$('#libraryAdd').onclick=startWizard;render();setInterval(()=>{if(dayIndex===new Date().getDay()){selected=currentItemIndex();render()}},60000);
